# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-20 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from nokia import NokiaAuth

from nokiaapp.utils import get_setting


def migrate_to_oauth2(apps, schema_editor):
    NokiaUser = apps.get_model("nokiaapp", "NokiaUser")
    auth = NokiaAuth(
        get_setting('NOKIA_CLIENT_ID'), get_setting('NOKIA_CONSUMER_SECRET'))
    for user in NokiaUser.objects.all():
        auth.migrate_from_oauth1(user.access_token, user.access_token_secret)


class Migration(migrations.Migration):

    dependencies = [
        ('nokiaapp', '0003_rename_nokiaapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='nokiauser',
            name='refresh_token',
            field=models.TextField(default='', help_text='OAuth2 refresh token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nokiauser',
            name='token_expiry',
            field=models.IntegerField(default=1534796425, help_text='Token expiration timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nokiauser',
            name='token_type',
            field=models.CharField(default='Bearer', help_text='Type of OAuth2 token', max_length=32),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_to_oauth2, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='nokiauser',
            name='access_token_secret',
        ),
        migrations.AlterField(
            model_name='measure',
            name='group',
            field=models.ForeignKey(help_text="The measurement's group", on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='nokiaapp.MeasureGroup'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measure_type',
            field=models.IntegerField(choices=[(1, 'Weight (kg)'), (4, 'Height (meter)'), (5, 'Fat Free Mass (kg)'), (6, 'Fat Ratio (%)'), (8, 'Fat Mass Weight (kg)'), (9, 'Diastolic Blood Pressure (mmHg)'), (10, 'Systolic Blood Pressure (mmHg)'), (11, 'Heart Pulse (bpm)'), (54, 'SP02(%)')], help_text="The measurement's type, one of: 1 (Weight (kg)), 4 (Height (meter)), 5 (Fat Free Mass (kg)), 6 (Fat Ratio (%)), 8 (Fat Mass Weight (kg)), 9 (Diastolic Blood Pressure (mmHg)), 10 (Systolic Blood Pressure (mmHg)), 11 (Heart Pulse (bpm)), 54 (SP02(%))"),
        ),
        migrations.AlterField(
            model_name='measure',
            name='unit',
            field=models.IntegerField(help_text='Power of ten the "value" attribute should be multiplied to to get the real value. Eg : value = 20 and unit=-1 means the value really is 2.0'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='value',
            field=models.IntegerField(help_text='Value for the measure in S.I units (kilogram, meters, etc.). Value should be multiplied by 10 to the power of "unit" to get the real value.'),
        ),
        migrations.AlterField(
            model_name='measuregroup',
            name='attrib',
            field=models.IntegerField(choices=[(0, 'Captured by a device, not ambiguous'), (1, 'Captured by a device, may belong to other user'), (2, 'Manually entered by user'), (4, 'Manually entered, may not be accurate')], help_text="The group's attribution, one of: 0 (Captured by a device, not ambiguous), 1 (Captured by a device, may belong to other user), 2 (Manually entered by user), 4 (Manually entered, may not be accurate)"),
        ),
        migrations.AlterField(
            model_name='measuregroup',
            name='category',
            field=models.IntegerField(choices=[(1, 'Real measurements'), (2, 'User objectives')], help_text="The group's category, one of: 1 (Real measurements), 2 (User objectives)"),
        ),
        migrations.AlterField(
            model_name='measuregroup',
            name='date',
            field=models.DateTimeField(help_text='The datetime of the measurement(s)'),
        ),
        migrations.AlterField(
            model_name='measuregroup',
            name='grpid',
            field=models.IntegerField(help_text='The group ID, assigned by nokia'),
        ),
        migrations.AlterField(
            model_name='measuregroup',
            name='updatetime',
            field=models.DateTimeField(help_text='The last updated datetime of the measurement(s)'),
        ),
        migrations.AlterField(
            model_name='measuregroup',
            name='user',
            field=models.ForeignKey(help_text="The group's user", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nokiauser',
            name='access_token',
            field=models.TextField(help_text='OAuth2 access token'),
        ),
        migrations.AlterField(
            model_name='nokiauser',
            name='last_update',
            field=models.DateTimeField(blank=True, help_text="The datetime the user's nokia data was last updated", null=True),
        ),
        migrations.AlterField(
            model_name='nokiauser',
            name='nokia_user_id',
            field=models.IntegerField(help_text='The nokia user ID'),
        ),
        migrations.AlterField(
            model_name='nokiauser',
            name='user',
            field=models.OneToOneField(help_text='The user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
